monolog:
    use_microseconds: true,
    channels: [ 'main', 'app', 'rabbit' ],
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/main.log"
            level: debug
            channels: ["!event", "!rabbit"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
