monolog:
    use_microseconds: true,
    channels: [ 'main', 'app', 'bot', 'client' ],
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [401, 422, 404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/app.json"
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!rabbit"]
        bot:
            type: rotating_file
            max_files: 5
            channels: ["bot"]
            path: "%kernel.logs_dir%/%kernel.environment%/bot.json"
            level: debug
            formatter: 'monolog.formatter.custom_processor'
        client:
            type: rotating_file
            max_files: 5
            channels: [ "client" ]
            path: "%kernel.logs_dir%/%kernel.environment%/client.json"
            level: debug
            formatter: 'monolog.formatter.custom_processor'
